### ISSUE TITLE
Error: column index out of bounds

### ISSUE THREAD

**Issue by jfredfan** [THUDM/ProNE#16]
Hi - I installed ProNE (python 2.7) and was able to train embeddings for the PPI example with the command:
python proNE.py -graph data/PPI.ungraph -emb1 emb/PPI_sparse.emb -emb2 emb/PPI_spectral.emb
 -dimension 128 -step 10 -theta 0.5 -mu 0.2

However, when applied on my own data it ran into the following exception. Appreciate any advice what went wrong. The input is about 50MB so I don't know how to share it for debugging. Thanks much in advance.

Traceback (most recent call last):
  File "proNE.py", line 178, in <module>
    main()
  File "proNE.py", line 157, in main
    model = ProNE(args.graph, args.emb1, args.emb2, args.dimension)
  File "proNE.py", line 31, in __init__
    matrix0[e[0], e[1]] = 1
  File "/home/m1234567/miniconda2/lib/python2.7/site-packages/scipy/sparse/lil.py", line 332, in __setitem__
    self.rows, self.data, i, j, x)
  File "_csparsetools.pyx", line 63, in scipy.sparse._csparsetools.lil_insert
  File "_csparsetools.pyx", line 89, in scipy.sparse._csparsetools.lil_insert
IndexError: column index (17654) out of bounds

**Comment by jfredfan** [comment]
I think I figured out. When preparing the input node pairs, there is no need to perform dedup or remove self-link. Those preprocesses seem to cause problem instead.

**Comment by shuiyuejihua** [comment]
Node index is continuous without interruption.

**Comment by XquaKe** [comment]
> Node index is continuous without interruption.
The problem still exists

**Comment by XquaKe** [comment]
Did you solve this problem?
